spring:
  datasource:
    url: jdbc:mysql://robot-do-user-1968994-0.b.db.ondigitalocean.com:25060/dotsenko?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: doadmin
    password: AVNS_I6wlDKjGszZn1wvLr9t
    h2:
      console:
        enabled: true
        path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
